# Use the official Python image as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the application files into the container
COPY app.py requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pymongo

# Expose the port your Flask app will run on
EXPOSE 3002

# Start the Flask application
CMD ["gunicorn", "-b", "0.0.0.0:3002", "app:app"]
