# Use the official Node.js LTS (Long-Term Support) image
FROM node:lts

# Set the working directory in the container
WORKDIR /app

# Install the latest version of npm
RUN npm install -g npm@latest

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install express cors express-http-proxy

# Copy the rest of the application source code to the container
COPY . .

# Expose the port your app is running on
EXPOSE 3001

# Define the command to run your Node.js application
CMD ["node", "server.js"]
